name: Run Konveyor main branch tests

on: ["push", "pull_request"]

concurrency:
  group: Konveyor-main-branch-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    uses: ./.github/workflows/global-ci.yml
    with:
      tag: latest
      api_tests_ref: main
      run_api_tests: true
      ui_tests_ref: main
      run_ui_tests: true
