name: Run Konveyor nightly main branch tests

on:
  schedule:
    - cron: "5 3 * * *"
  workflow_dispatch:

jobs:
  main-nightly:
    uses: ./.github/workflows/global-ci.yml
    with:
      tag: latest
      api_tests_ref: main
      run_api_tests: true
      ui_tests_ref: main
      # Disabled while we wait for stability
      run_ui_tests: false
